import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';
import { useOpenCv } from 'opencv-react';

const Scan: NextPage = () => {
  const { openCvLoaded, cv } = useOpenCv();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>{openCvLoaded && 'loaded'}</div>
      </main>
    </>
  );
};

export default Scan;
